import Link from "next/link";
import { notFound } from "next/navigation";
import { CaseExplanation } from "@/components/case-explanation";
import { getCaseById } from "@/lib/scoring";

export default async function CaseDetail({ params }: { params: Promise<{ ringId: string }> }) {
  const ring = getCaseById((await params).ringId);
  if (!ring) notFound();
  const initial = { summary: ring.explanation, evidence: ring.evidence.map((item) => item.label), recommendation: "Manual investigation only" as const, limitations: ring.limitations, source: "deterministic" as const };
  return <main className="case-page"><header className="case-top"><Link href="/dashboard">← Back to overview</Link><span>READ-ONLY CASEWORK</span></header><div className="case-content"><div className="case-breadcrumb">INVESTIGATION QUEUE / {ring.id}</div><div className="case-title"><div><h1>Potential coordinated<br/>promotion abuse</h1><p>{ring.accountIds.length} accounts · {ring.couponCode} · created for manual investigation</p></div><div className="case-score"><span>Risk confidence</span><strong>{ring.confidence}</strong><small>/100</small></div></div><div className="case-warning">This case is a prioritized hypothesis, not proof of wrongdoing. No order, payment, account, or coupon action is available in Sentinel.</div><div className="detail-grid"><section className="network-card"><div className="detail-card-heading"><div><span>ENTITY RELATIONSHIP GRAPH</span><h2>Linked evidence surface</h2></div><b>{ring.accountIds.length} accounts</b></div><div className="detail-network"><div className="network-core">{ring.id}</div>{ring.accountIds.map((id, index) => <div key={id} className={`network-account n${index}`}>{id}</div>)}<div className="network-signal signal-one">DEVICE<br/><b>dev_91</b></div><div className="network-signal signal-two">PAYMENT<br/><b>•••• 1042</b></div><div className="network-signal signal-three">COUPON<br/><b>{ring.couponCode}</b></div></div><div className="network-legend"><span>● Account</span><span>◆ Shared signal</span><span>◎ Ring</span></div></section><CaseExplanation ringId={ring.id} initial={initial}/></div><div className="detail-grid lower"><section className="evidence-detail"><div className="detail-card-heading"><div><span>EVIDENCE LEDGER</span><h2>Every link is inspectable</h2></div></div>{ring.evidence.map((evidence) => <article key={evidence.kind}><span className={`evidence-mark ${evidence.strength}`}>{evidence.kind.slice(0, 1).toUpperCase()}</span><div><strong>{evidence.label}</strong><p>{evidence.detail}</p><small>Accounts: {evidence.accountIds.join(", ")}</small></div><b>+{evidence.contribution}</b></article>)}</section><aside className="exposure-detail"><span>ESTIMATED PROMOTIONAL EXPOSURE</span><strong>₹{ring.exposureInr.toLocaleString("en-IN")}</strong><p>{ring.couponCode} redeemed by {ring.accountIds.length} linked accounts.</p><div><span>Case status</span><b>Investigate</b></div><div><span>Automated action</span><b>None</b></div></aside></div></div></main>;
}
